//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_market()
        {
            this.Marketlocks = new HashSet<Marketlock>();
            this.Payment_Market = new HashSet<Payment_Market>();
            this.Revenue_Table = new HashSet<Revenue_Table>();
        }
    
        public string BookingNumber { get; set; }
        public int CustomerID { get; set; }
        public string ShopName { get; set; }
        public string EmployeeID { get; set; }
        public string Marketlock_ID { get; set; }
        public string Typesofproductssold { get; set; }
        public string Numberofproducts { get; set; }
        public Nullable<decimal> LockPrice { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Paymentstatus { get; set; }
        public string BookingDetails { get; set; }
        public Nullable<int> ReservationPeriod { get; set; }
        public Nullable<System.DateTime> Dateofreservation { get; set; }
        public Nullable<System.DateTime> Bookingenddate { get; set; }
        public Nullable<System.DateTime> TransactionStartDate { get; set; }
        public Nullable<int> LockReturnID { get; set; }
        public Nullable<int> UtilityID { get; set; }
    
        public virtual Category_product Category_product { get; set; }
        public virtual Customer_market Customer_market { get; set; }
        public virtual Employee_market Employee_market { get; set; }
        public virtual Lock_return Lock_return { get; set; }
        public virtual Marketlock Marketlock { get; set; }
        public virtual Utility_Market Utility_Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketlock> Marketlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Market> Payment_Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue_Table> Revenue_Table { get; set; }
    }
}
