//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_market()
        {
            this.Booking_market = new HashSet<Booking_market>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeID_card_number { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeLastname { get; set; }
        public string EmployeeSex { get; set; }
        public Nullable<System.DateTime> Employeebirthday { get; set; }
        public string Employeeaddress { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_market> Booking_market { get; set; }
    }
}
