//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lock_return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lock_return()
        {
            this.Booking_market = new HashSet<Booking_market>();
        }
    
        public int Lock_ReturnID { get; set; }
        public string BookingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerLastname { get; set; }
        public string Marketlock_ID { get; set; }
        public string BookingDetails { get; set; }
        public Nullable<System.DateTime> LockReturnDate { get; set; }
        public Nullable<int> LateReturnPeriod { get; set; }
        public string FineTypeID1 { get; set; }
        public string FineTypeID2 { get; set; }
        public Nullable<decimal> FineSum { get; set; }
        public string LockSize { get; set; }
        public Nullable<System.DateTime> Bookingenddate { get; set; }
        public string LockReturnStatus { get; set; }
        public string FinePayStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_market> Booking_market { get; set; }
        public virtual Fine_market Fine_market { get; set; }
        public virtual Fine_market Fine_market1 { get; set; }
    }
}
