//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marketlock()
        {
            this.Booking_market = new HashSet<Booking_market>();
        }
    
        public string Marketlock_ID { get; set; }
        public string MarketZonename { get; set; }
        public string Marketlock_Size { get; set; }
        public Nullable<decimal> PriceforFrequenters { get; set; }
        public Nullable<decimal> PriceforIrregulars { get; set; }
        public string Marketlock_Status { get; set; }
        public string BookingNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_market> Booking_market { get; set; }
        public virtual Booking_market Booking_market1 { get; set; }
    }
}
