//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_market
    {
        public int MemberID { get; set; }
        public string MemberID_card_number { get; set; }
        public string MemberName { get; set; }
        public string MemberLast { get; set; }
        public string MemberSex { get; set; }
        public Nullable<System.DateTime> MemberBirthday { get; set; }
        public string MemberPhone { get; set; }
        public string MemberEmail { get; set; }
        public string MemberUsername { get; set; }
        public string MemberStatus { get; set; }
        public string MemberAccesslevel { get; set; }
        public string MemberInformation { get; set; }
    }
}
