//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FleamarketEntities : DbContext
    {
        public DB_FleamarketEntities()
            : base("name=DB_FleamarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_market> Booking_market { get; set; }
        public virtual DbSet<Category_product> Category_product { get; set; }
        public virtual DbSet<Customer_market> Customer_market { get; set; }
        public virtual DbSet<Employee_market> Employee_market { get; set; }
        public virtual DbSet<Fine_market> Fine_market { get; set; }
        public virtual DbSet<Lock_return> Lock_return { get; set; }
        public virtual DbSet<Login_Account> Login_Account { get; set; }
        public virtual DbSet<Marketlock> Marketlocks { get; set; }
        public virtual DbSet<Member_market> Member_market { get; set; }
        public virtual DbSet<Payment_Market> Payment_Market { get; set; }
        public virtual DbSet<Revenue_Table> Revenue_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Utility_Market> Utility_Market { get; set; }
    }
}
