//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Market
    {
        public int PaymentID { get; set; }
        public string PaymentType { get; set; }
        public string BookingNumber { get; set; }
        public string SlipPath { get; set; }
        public byte[] SlipImg { get; set; }
    
        public virtual Booking_market Booking_market { get; set; }
    }
}
