//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue_Table
    {
        public int RevenueID { get; set; }
        public string RevenueType { get; set; }
        public Nullable<decimal> RevenueNum { get; set; }
        public string BookingNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Booking_market Booking_market { get; set; }
    }
}
