//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ระบบจองล็อคตลาด
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility_Market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utility_Market()
        {
            this.Booking_market = new HashSet<Booking_market>();
        }
    
        public int UtilityID { get; set; }
        public Nullable<decimal> UtilityAmount { get; set; }
        public Nullable<System.DateTime> Billing_Date { get; set; }
        public string BookingNumber { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> DurationUsed { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerLname { get; set; }
        public string BookingDetail { get; set; }
        public string LockID { get; set; }
        public string MarketZonename { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_market> Booking_market { get; set; }
    }
}
